WebApplication1/Models/Reservations.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class Reservations
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int GuestID { get; set; }
        public int RoomID { get; set; }

        [Required(ErrorMessage = "Check-in date is required.")]
        [DataType(DataType.Date, ErrorMessage = "Invalid date format.")]
        public DateTime CheckInDate { get; set; }

        [Required(ErrorMessage = "Check-out date is required.")]
        [DataType(DataType.Date, ErrorMessage = "Invalid date format.")]
        public DateTime CheckOutDate { get; set; }
        public float Income { get; set; }
        public int Status { get; set; }
    }
}

WebApplication1/Models/Room.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class Room
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage ="Must choose type")]
        public string RoomNumber { get; set; } = null!;
        public int Floor { get; set; }
        public string RoomTypeName { get; set; } = null!;
        public string? Service { get; set; }
        public float Price { get; set; }
        public string? Description { get; set; }

        public bool IsActive { get; set; }
    }
}

WebApplication1/Models/RoomType.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class RoomType
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RoomTypeId{ get; set; }
        public string RoomTypeName {  get; set; }
        public int Area {  get; set; }
        public float Price {  get; set; }
        public string Bed{ get; set; }
        public string linkimg1{get; set; }
        public string linkimg2 { get; set; }
        public string linkimg3 { get; set; }
        public string linkimg4 { get; set; }
        public string linkimg5 { get; set; }
    }
}

WebApplication1/Models/Staff.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class Staff
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? Role { get; set; }

        public string? PhoneNumber { get; set; }

        public string? Gender { get; set; }

        public DateTime startWorkTime { get; set; }

        public string? Address { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

WebApplication1/Controllers/ManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ManagementController : Controller
    {

        private readonly HotelContext database;

        public ManagementController(HotelContext context)
        {
            this.database = context;
        }
        
        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            HttpContext.Session.Remove("Username:");
            return RedirectToAction("Login", "Hotel");
        }

        public IActionResult Staff()
        {
            var username = HttpContext.Session.GetString("Username");
            ViewBag.Username = username;

            ViewBag.Role = HttpContext.Session.GetString("Role");

            var allRes = database.Reservations.ToList();

            foreach(var res in allRes)
            {
                Reservations temp = new Reservations();
                int roomId = temp.RoomID;

                bool hasReservations = allRes.Any(r => r.RoomID == roomId);

                if(hasReservations)
                {
                    Room room = database.Rooms.FirstOrDefault(r => r.Id == roomId);
                    if(room != null)
                    {
                        room.IsActive = false;
                    }
                }
            }

            var totalRoom = database.Rooms.Count();
            var inhouseGuest = database.Guests.Count();
            var resCount = database.Reservations.Count();
            float income = 0;
            foreach(var temp in database.Reservations)
            {
                income += temp.Income;     
            }
            var countActiveRooms = database.Rooms
                .Count(r => r.IsActive == true);

            ViewBag.totalRoom = totalRoom;
            ViewBag.RoomActiveCount = countActiveRooms;

            ViewBag.guestCount = inhouseGuest;
            ViewBag.resCount = resCount;

            ViewBag.Income = income;

            return View();
        }
        public IActionResult StaffList(int pg = 1)
        {
            List<Staff> staff = database.Staffs.ToList();
            const int pageSize = 8;
            if (pg < 1) pg = 1;
            int recordCount = staff.Count();
            var pager = new Pager(recordCount, pg, pageSize);
            int recordSkip = (pg - 1) * pageSize;
            var data = staff.Skip(recordSkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;

            return View("StaffList", data);
        }

        public IActionResult Room(int pg = 1)
        {
            List<Room> room = database.Rooms.ToList();
            const int pageSize = 8;
            if (pg < 1) pg = 1;
            int recordCount = room.Count();
            var pager = new Pager(recordCount, pg, pageSize);
            int recordSkip = (pg - 1) * pageSize;
            var data = room.Skip(recordSkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;

            return View("Room", data);
        }

        public IActionResult RoomByName(string name, int pg = 1)
        {

            var data = database.Rooms
                .Where(r => r.RoomTypeName == name)
                .ToList();
            
            return PartialView("_RoomData", data);
        }

        public IActionResult Reservation(int pg = 1)
        {
            List<Reservations> reservation = database.Reservations.ToList();
            const int pageSize = 8;
            if (pg < 1) pg = 1;
            int recordCount = reservation.Count();
            var pager = new Pager(recordCount, pg, pageSize);
            int recordSkip = (pg - 1) * pageSize;
            var data = reservation.Skip(recordSkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;

            ViewBag.recordCount = recordCount;

            return View("Reservation", data);
        }

        public IActionResult GuestList(int pg = 1)
        {
            List<Guest> guest = database.Guests.ToList();
            const int pageSize = 8;
            if (pg < 1) pg = 1;
            int recordCount = guest.Count();
            var pager = new Pager(recordCount, pg, pageSize);
            int recordSkip = (pg - 1) * pageSize;
            var data = guest.Skip(recordSkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;

            ViewBag.recordCount = recordCount;

            return View("GuestList", data);
        }

        public IActionResult Delete(int? id)
        {
            if(id == null || database.Reservations == null)
            {
                return NotFound();
            }

            var reservation = database.Reservations
                .FirstOrDefault(m => m.ID == id);

            if(reservation == null)
            {
                return NotFound();
            }
            return View(reservation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id) 
        {
            if(database.Reservations == null)
            {
                return Problem("Entity set 'Reservations' is null");
            }

            var res = database.Reservations.Find(id);
            int roomID = id;

            var room = database.Rooms.Find(roomID);
            var guest = database.Guests.Find(res.GuestID);
            if (room != null && database.Reservations != null && guest != null)
            {
                room.IsActive = true;
                database.Guests.Remove(guest);
                database.Reservations.Remove(res);
            }
            database.SaveChanges();



            return RedirectToAction("Reservation");
        }

        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var guest = database.Guests.Find(id);

            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Guest guest)
        {
            if(id != guest.ID)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {
                try
                {
                    database.Update(guest);
                    database.SaveChanges();
                }
                catch
                {
                    if(!GuestExist(guest.ID))
                    {
                        return NotFound();
                    } else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(GuestList));
            }
            return View(guest);
        }

        private bool GuestExist(int id)
        {
            return database.Guests.Any(e => e.ID == id);   
        }
    }
}

WebApplication1/ViewComponents/RoomTypeNameViewComponent.cs
using WebApplication1.Data;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using System.Collections.Generic;
using System.Linq;
namespace WebApplication1.ViewConponents
{
    public class RoomTypeNameViewComponent : ViewComponent
    {
        HotelContext database;
        List<Room> rooms;

        public RoomTypeNameViewComponent(HotelContext _context)
        {
            database = _context;
            rooms = database.Rooms.ToList();
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderRoomTypeName", rooms);
        }

    }
}

WebApplication1/Views/Management/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Management/Main.cshtml";
}

@model Reservations
<div class=" mx-2 ms-2">

    <h1>Delete</h1>
    <h3>Are you sure you want to delete this?</h3>
    <br />
    <h4>Resevation</h4>
    <hr />

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GuestID)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.GuestID)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomID)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.RoomID)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CheckInDate)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.CheckInDate)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CheckOutDate)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.CheckOutDate)
        </dt>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Reservation" class="btn btn-success">Back to list</a>

    </form>
</div>

WebApplication1/Views/Management/Edit.cshtml
@model Guest
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Management/Main.cshtml";
}

<div class="container mt-5">
    <h1>Edit Learner</h1>

    <div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <form asp-controller="Management" asp-action="Edit" method="post" class="mt-3">
            <input type="hidden" asp-for="ID" />

            <div style="margin-top: 7px" class="form-group row">
                <label asp-for="FirstName" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div style="margin-top: 7px" class="form-group row">
                <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div style="margin-top: 7px" class="form-group row">
                <label asp-for="Email" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div style="margin-top: 7px" class="form-group row">
                <label asp-for="PhoneNumber" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
            </div>
            <div style="margin-top: 10px" class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

WebApplication1/Views/Management/GuestList.cshtml
@model IEnumerable<Guest>

@{
    Layout = null;
    Pager pager = new Pager();
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
    }
}

<h1 class="text-center mt-5 border text-uppercase"> Guest</h1>

<div>
    @if (ViewBag.recordCount == 0)
    {
        <h1 class="mt-3 text-center">No records have been made!</h1>
    }
    else
    {
        <form asp-controller="Management" asp-action="GuestList">
            <p>
                Title: <input type="text" name="SearchString" />
                <input type="submit" value="Filter">
            </p>
        </form>
        <table class="table table-hover table-responsive">

            <thead class="thead-dark">
                <tr class="text-center">
                    <th>ID</th>
                    <th style="width:25%">First Name</th>
                    <th style="width:25%">Last Name</th>
                    <th style="width:20%">Email</th>
                    <th style="width:20%">Phone Number</th>
                    <th style="width:10%">Function</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var g in Model)
                {
                    <tr class="text-center">
                        <td>@g.ID</td>
                        <td>@g.FirstName</td>
                        <td>@g.LastName</td>
                        <td>@g.Email</td>
                        <td>@g.PhoneNumber</td>
                        <td class="">
                            <a asp-action="Edit" asp-route-id="@g.ID"><i class="fa-regular fa-pen-to-square"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="container" id="paging">
            <ul class="pagination">
                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-page="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-pg="@(pager.CurrentPage -1)">Previous</a>
                    </li>
                }
                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link load-page" asp-route-pg="@pge">@pge</a>
                    </li>
                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        </div>
    }
</div>

WebApplication1/Views/Management/Main.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/datatables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
</head>

<style>
    .left-main p {
        font-size: 25px;
        color: white;
        border-bottom: 1px solid white;
        border-radius: 5px
    }

    .left-main img {
        margin-top: 30px;
        margin-left: 55px;
    }

    .left-main ul {
        list-style: none;
        color: white;
        font-size: 20px;
    }

    .left-main li a {
        text-decoration: none;
        color: white;
    }

    .left-main li:not(:last-child) {
        margin-bottom: 10px;
    }

    .left-main h5 {
        color: white;
        font-size: 30px;
        margin-top: 50px;
        padding: 10px;
    }

</style>

<body>
    <header>
        <div class="d-flex p-2 bg-light justify-content-between">
            <h2 class="ml-5">Moonlight Hotel</h2>
            <a class="mr-5 mt-2"><i class="fa-solid fa-bars"></i></a>
        </div>
    </header>

    <main class="row">
        <div class="left-main col-2 bg-info container">
            <img src="~/img/userPic.png">
            <p class="mt-2 text-center">@ViewBag.Username</p>
            <div>
                <h5>Statistics</h5>
                <ul>
                    <li class="d-flex align-items-center">
                        <a href="javascript:void(0)" onclick="loadContent('Staff', 'Management')">Home&emsp;&emsp;&emsp;&emsp;<i class="fa-solid fa-house"></i></a>
                    </li>
                    <li>
                        <a href="javascript:void(0)" onclick="loadContent('Room', 'Management')">Rooms&emsp;&emsp;&emsp;&ensp;<i class="fa-solid fa-bed"></i></a>
                        
                     </li>
                    <li>
                        <a href="javascript:void(0)" onclick="loadContent('Reservation', 'Management')">Reservation &emsp;<i class="fa-solid fa-receipt"></i></a>
                        
                     </li>
                    <li>
                        <a href="javascript:void(0)" onclick="loadContent('GuestList', 'Management')">Guests &emsp;&emsp;&emsp;&nbsp;<i class="fa-regular fa-user"></i></a>
                        
                    </li>
                    @if(ViewBag.Role == "Manager")
                    {
                        <li>
                            <a href="javascript:void(0)" onclick="loadContent('StaffList', 'Management')">Staffs &emsp;&emsp;&emsp;&ensp;&ensp;<i class="fa-solid fa-user-tie"></i></a>
                        </li>
                    }
                    <li>
                        <a asp-action="LogOut" asp-controller="Management" class="btn btn-danger text-white mt-5">Log out</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-10" id="content-placeholder">
            @RenderBody()
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/js/datatables.min.js"></script>
    <script src="~/js/scripts.js"></script>
    @RenderSection("Scripts", required:false)
</body>
</html>

    <script>
        function loadContent(action, controller)
        {
            $('#content-placeholder').empty();

            $.get('/Management/' + action, function (data) {
                $('#content-placeholder').html(data);
            });
        }
    </script>

WebApplication1/Views/Management/Reservation.cshtml
@{
    Layout = null;

    Pager pager = new Pager();
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
    }
}

@model IEnumerable<Reservations>

<h1 class="text-center mt-5 border text-uppercase"> Reservation</h1>

<div>
    @if(ViewBag.recordCount == 0)
    {
        <h1 class="mt-3 text-center">No records have been made!</h1>
    } else {
    <table class="table table-hover table-responsive">

        <thead class="thead-dark">
            <tr class="text-center">
                    <th style="width:10%">ID</th>
                    <th style="width:15%">Created At</th>
                    <th style="width:15%">Update At</th>
                    <th style="width:15%">GuestID</th>
                    <th style="width:15%">RoomID</th>
                    <th style="width:15%">CheckInDate</th>
                    <th style="width:15%">CheckOutDate</th>
                    <th style="width:15%">Income</th>
                    <th style="width:10%">Status</th>
                    <th style=""> Function</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var r in Model)
            {
                <tr class="text-center">
                    <td>@r.ID</td>
                    <td>@r.CreatedDate</td>
                    <td>@r.UpdatedAt</td>
                    <td>@r.GuestID</td>
                    <td>@r.RoomID</td>
                    <td>@r.CheckInDate</td>
                    <td>@r.CheckOutDate</td>
                    <td>@r.Income</td>
                    <td>@r.Status</td>
                    <td class="">
                            <a asp-action="Delete" asp-route-id="@r.ID"><i class="fa-solid fa-trash-can"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

        <div class="container" id="paging">
            <ul class="pagination">
                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-page="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-pg="@(pager.CurrentPage -1)">Previous</a>
                    </li>
                }
                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link load-page" asp-route-pg="@pge">@pge</a>
                    </li>
                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link load-page" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        </div>
    }
</div>

WebApplication1/Views/Management/Room.cshtml
@model IEnumerable<Room>

@{
    Layout = null;

    Pager pager = new Pager();
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
    }
}


<h1 class="text-center mt-5 border text-uppercase" id="title"> Room List </h1>

<div>
    @await Component.InvokeAsync("RoomTypeName")
</div>

<div id="roomListContainer">
<table class="table table-hover table-responsive">

    <thead class="thead-dark">
        <tr class="text-center">
            <th>Room ID</th>
            <th>Room Type</th>
            <th>Floor</th>
            <th>Room Number</th>
            <th>Price</th>
            <th>Description</th>
            <th>Service</th>
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var r in Model)
        {
            <tr>
                <td>@r.Id</td>
                <td>@r.RoomTypeName</td>
                <td>@r.Floor</td>
                <td>@r.RoomNumber</td>
                <td>@r.Price</td>
                <td>@r.Description</td>
                <td>@r.Service</td>
                <td>@r.IsActive</td>
            </tr>
        }
    </tbody>
</table>
</div>
<div class="container" id="paging">
        <ul class="pagination">
            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link load-page" asp-route-page="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link load-page" asp-route-pg="@(pager.CurrentPage -1)">Previous</a>
                </li>
            }
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link load-page" asp-route-pg="@pge">@pge</a>
                </li>
            }
            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link load-page" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link load-page" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }
        </ul>
</div>



@section Scripts {
    <script>
            $("li").click(function (e) {
                var page = $(this).data("page");
                var roomTypeName = $(this).attr("id");
                var temp = document.getElementById("paging");
                $.ajax({
                    url: "/Management/RoomByName",
                    data: { name: roomTypeName},
                    success: function (data) {
                        $("div#roomListContainer").html(data);
                        temp.style.display = "none";
                    }
                });

            });

    </script>
}

WebApplication1/Views/Management/Staff.cshtml
@{
    Layout = null;
}
    <style>
        .nav-bar {
            align-items: center;
            padding: 10px;
            color: black;
            border-bottom: 2px solid gray;
        }

            .nav-bar h1 {
                margin-left: 20px;
            }

        .main-left {
            background-color: gray;
            border-bottom-right-radius: 10px;
            height: 100px;
        }

            .main-left a {
                text-decoration: none;
                color: white;
            }

        .timebox {
            font-size: 30px;
            background-color: #3D2C8D;
            color: white;
        }

        .card {
            font-size: 20px;
        }

        .crd p {
            padding: 100px;
        }
    </style>

    <div class="main row">
    </div>
    <div class="timebox">
        <p id="time" class="text-center"></p>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card text-center">
                <div class="card-body">
                    <div class="card-title mb-5"><h3>Rooms</h3></div>
                    <p class="card-text">
                        Rooms total: @ViewBag.totalRoom
                        <br />
                        Rooms available: @ViewBag.RoomActiveCount
                    </p>
                </div>
            </div>
        </div>

        <div class="col-4 mt-4">
            <div class="card text-center">
                <div class="card-body crd">
                    <div class="card-title"><h3>In-house guests</h3></div>
                    <p style="font-size:40px">@ViewBag.guestCount</p>

                </div>
            </div>
        </div>

        <div class="col-4 mt-4">
            <div class="card text-center">
                <div class="card-body crd">
                    <div class="card-title"><h3>Income</h3></div>
                    <p style="font-size:30px">@ViewBag.Income VND</p>
                </div>
            </div>
        </div>

        <div class="col-4 mt-4">
            <div class="card text-center">
                <div class="card-body crd">
                    <div class="card-title"><h3>Res count</h3></div>
                    <p style="font-size:40px">@ViewBag.resCount</p>
                </div>
            </div>
        </div>
    </div>

<script>

    const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

    function updateClock() {
        const currentDate = new Date();

        const dayOfWeek = days[currentDate.getDay()];
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth() + 1;
        const day = currentDate.getDate();
        const hours = currentDate.getHours();
        const minutes = currentDate.getMinutes();
        const seconds = currentDate.getSeconds();

        document.getElementById("time").innerHTML = `${dayOfWeek} ${day}/${month}/${year}  ${hours}:${minutes}:${seconds}`;
    }

    updateClock();
    setInterval(updateClock, 1000);
</script>