WebApplication1/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HotelController : Controller
    {
        private readonly HotelContext database;
        public float totalMoney;

        public HotelController(HotelContext context)
        {
            this.database = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Gallery()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(Staff inputData)
        {
            var user = database.Staffs.FirstOrDefault(s =>
                s.Username == inputData.Username && s.Password == inputData.Password);

            if (user != null)
            {
                HttpContext.Session.SetString("Username", user.Username);
                HttpContext.Session.SetString("Role", user.Role);

                if (user.Role == "Staff" || user.Role == "Manager")
                {
                    return RedirectToAction("Staff", "Management");
                }
            }

            // If authentication fails, return to the login view
            return View();
        }


        //trang room//
        public IActionResult SUPERIOR()
        {
            return View();
        }
        public IActionResult DELUXE()
        {
            return View();
        }
        public IActionResult SENIOR_DELUXE()
        {
            return View();
        }
        public IActionResult FAMILY_ROOM()
        {
            return View();
        }

        // heets trang room//

        public IActionResult Rooms()
        {
            var lstLoaiPhong = database.RoomTypes.ToList();
            return View(lstLoaiPhong);
        }
        public IActionResult Book() {
            return View();
        }

        [HttpGet]
        public IActionResult BookConfirmed() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult BookConfirmed(GuestRoom_Booking data)
        {
            if(ModelState.IsValid)
            {
                if (data.reservations.CheckInDate >= data.reservations.CheckOutDate)
                {
                    ModelState.AddModelError("reservations.CheckInDate", "Check-in date must be earlier than the check-out date.");
                    return View("Book");
                }

                if(!database.Rooms.Any(r=>r.IsActive && r.RoomNumber == data.room.RoomNumber))
                {
                    ModelState.AddModelError("RoomNumber","Chosen room is booked");
                    return View("Book");
                }

                Guest newGuest = new()
                {
                    FirstName = data.guest.FirstName,
                    LastName = data.guest.LastName,
                    Email = data.guest.Email,
                    PhoneNumber = data.guest.PhoneNumber,
                };

                Room room = new()
                {
                    RoomNumber = data.room.RoomNumber,
                    Floor = data.room.Floor,
                    RoomTypeName = data.room.RoomTypeName,
                    IsActive = true,
                };
                   database.Guests.Add(newGuest);
                   database.SaveChanges();

                float rate = 1f; // Default rate

                if (data.reservations.CheckInDate.Hour >= 0 && data.reservations.CheckInDate.Hour < 9)
                {
                    rate = 0.5f;
                }
                else if (data.reservations.CheckInDate.Hour >= 9 && data.reservations.CheckInDate.Hour < 17)
                {
                    rate = 0.3f;
                }
                else if (data.reservations.CheckInDate.Hour >= 17 && data.reservations.CheckInDate.Hour < 24)
                {
                    rate = 1.0f;
                }

                float roomRate = 0.0f;

                if (data.room.RoomTypeName == "Superior")
                {
                    roomRate = 1000000;
                }
                else if (data.room.RoomTypeName == "Deluxe")
                {
                    roomRate = 1200000;
                }
                else if (data.room.RoomTypeName == "Senior Deluxe")
                {
                    roomRate = 1400000;
                }
                else if (data.room.RoomTypeName == "Family Room")
                {
                    roomRate = 1600000;
                }

                totalMoney = (float)((data.reservations.CheckOutDate.Day - data.reservations.CheckInDate.Day) * roomRate * rate);

                int newGuestid = newGuest.ID;
                int roomID = database.Rooms
                     .Where(r => r.RoomNumber == data.room.RoomNumber && r.Floor == data.room.Floor && r.RoomTypeName == data.room.RoomTypeName)
                     .Select(r => r.Id)
                     .FirstOrDefault();

                Reservations reservations = new()
                {
                    CreatedDate = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    GuestID = newGuestid,
                    RoomID = roomID,
                    CheckInDate = data.reservations.CheckInDate,
                    CheckOutDate = data.reservations.CheckOutDate,
                    Income = totalMoney,
                    Status = 1,
                };

                    database.Reservations.Add(reservations);
                    database.SaveChanges();
                TempData["successMessage"] = "Employee created successfully!";

                var reservedRoomIds = database.Reservations
                    .Select(res => res.RoomID)
                    .ToList();

                var roomsToDeactivate = database.Rooms.Where(r => reservedRoomIds.Contains(r.Id));

                foreach (var temp in roomsToDeactivate)
                {
                    temp.IsActive = false;
                }

                database.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();   
        }
    
    }
}

WebApplication1/Views/Shared/Footer.cshtml
    <hr style="height:2px;border:none;color:#1C0C5B;background-color:#1C0C5B;margin-top: 100px;" class="container">

    <div class="footer">
        <div class="container d-flex">
            <div class="col-4">
                <img src="/img/9232021.png" alt="" style="margin-bottom: 20px;">
                <p>(+84) 0258 390 9988</p>
                <p>info@moonlight.com</p>
                <p>624 Garden Lane</p>
            </div>
            <div class="col-5 text-uppercase">
                <p>Policy</p>
                <a href="#">Chính sách và quy định</a>
            </div>
            <div class="col-3 text-uppercase">
                <p>Phòng Nghỉ</p>
                <a href="#">Family Room</a>
                <br>
                <a href="#">Senior Deluxe</a>
                <br>
                <a href="#">Deluxe</a>
                <br>
                <a href="#">Superior</a>
            </div>
        </div>
    
        <div class="text-center">
            <p>2023 © Moonlight Hotel. All Right Reserved. Design and developed by me</p>
        </div>
    </div>

WebApplication1/Views/Shared/Header.cshtml
<style>
    .header a {
        background-image: linear-gradient( to right, #C996CC, #C996CC 50%, #1C0C5B 50% );
        background-size: 200% 100%;
        background-position: -100%;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        transition: all 0.3s ease-in-out;
    }

    .dropdown:hover .dropdown-menu {
        display: block;
    }

    .dropdown-menu {
        background: #B3A492;
    }

    .dropdown-item: hover {
        background: #B3A492;
    }

    .navbar {
        top: 0;
        width: 100%;
        z-index: 99;
        background-color: #D2E3C8;
        border-bottom: 1px solid #555;
    }
</style>


<nav class=" header navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <h1 class="col-xl-2 col-md-2 ">Moonlight</h1>
        <div class="collapse navbar-collapse col-md-8" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Hotel" asp-action="index">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" asp-controller="Hotel" asp-action="Rooms" nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Rooms
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item w-100" asp-controller="Hotel" asp-action="SUPERIOR">SUPERIOR</a></li>
                        <li><a class="dropdown-item" asp-controller="Hotel" asp-action="DELUXE">DELUXE</a></li>
                        <li><a class="dropdown-item" asp-controller="Hotel" asp-action="SENIOR_DELUXE">SENIOR DELUXE</a></li>
                        <li><a class="dropdown-item" asp-controller="Hotel" asp-action="FAMILY_ROOM">FAMILY ROOM</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Hotel" asp-action="Gallery">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Hotel" asp-action="Book">Book Now</a>
                </li>

            </ul>

        </div>

        <a class="nav-link" asp-controller="Hotel" asp-action="Login" style="color:#1C0C5B">Login</a>

    </div>
</nav> 

WebApplication1/Views/Shared/Main.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <partial name="Header"/>

    <main>
        @RenderBody()
    </main>
    
    <partial name ="Footer"/>
    <script src="~/js/scripts.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>